### ISSUE TITLE
[server/JM] instagrapi Login 관련 예외처리 

### ISSUE THREAD

**Issue by whitepaper907** [iamphj3/2023-KU-HACKERTON-SYMPHONY#1]
## 💜 instagrapi 로그인 관련 이슈
기능 테스트를 위해 코드 수정 후 서버 재로딩 시 로그인을 다시 시도
자주 서버를 다시 시작할 경우 인증코드를 입력해야하는 이슈 

## ✅ To Dos
- [x] 로그인 연결 유지 가능여부 확인
- [x] 연결 유지가 어려울 경우 해결방법 고안

**Comment by iamphj3** [comment]
인스타 로그인 이슈 관련해서!! 
나 지금 다른 프로젝트에서도 이거 이슈 해결하느라 오래 걸렸어서 해결 방법 공유합니당

일단 이거 이슈 해결하려면 
1. 막힐때마다 인스타 계정 새로 파서 다시 테스트하기
2. 인스타그램 뷰어 웹사이트 이용해서 웹 크롤링하기
3. 프록시 서버 구매하기

이정도 방법이 있고,

1 -> 이것도 계속 시도하면 또 인스타가 감지해서 언제 차단할지 모름 (`한 IP로 계속 부계정을 만드시면 해당 IP 주소는 오픈 프록시로 분류됩니다`)
2 -> 가져올 수 있는 데이터가 api 쓰는것보다 제한적임, 웹크롤링을 거쳐야 하기 때문에 속도 느려짐
3 -> instagrapi에서 제시하는 해결방법, 인스타그램에서 감지 못하게 ip를 계속 바꿔주는 원리인듯?, but 비용 발생
instagrapi 에서 제공하는 서비스는 [이거!](https://lamadava.com/p/3msyAKDX), 요금은 이 둘 중에서 선택하면 될 듯 (`$20충전-> 요청당 비용 $0.02` or` $50충전->요청당 비용 $0.0025`)
<img width="483" alt="image" src="https://github.com/iamphj3/2023-KU-HACKERTON-SYMPHONY/assets/73213437/687d4ef8-4c10-4675-8e7d-e4515236c6e6">

어떻게 할지 생각해보고 내일 회의때 의논해봅시다!
